Initial commit
Hayashi1729/twitter-clone pull request #3
Opened 2021-03-29 04:33 UTC by Hayashi1729

2021-04-20 05:43 UTC, MasashiYokota requested changes
コメントしました

2021-04-20 05:43 UTC, MasashiYokota commented on src/assets/js/vue/PostEdit.vue
> +    });
onMountedの中でやったほうが良いですね。あと、thenは使っては駄目です

2021-04-20 05:43 UTC, MasashiYokota commented on src/assets/js/vue/PostIndex.vue
> +    });
ここもonMountedでやったほうが良いです

2021-04-20 05:43 UTC, MasashiYokota commented on src/assets/js/vue/PostShow.vue
> +    });
ここも同様です

2021-04-20 05:43 UTC, MasashiYokota commented on src/assets/js/vue/UserEdit.vue
> +    });
ここも

2021-04-20 05:43 UTC, MasashiYokota commented on src/assets/js/vue/UserIndex.vue
> +    });
ここも

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project/twitter.ex
> +  end
Repo.all()するときは、絶対にorder_byを入れて下さい

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project/twitter.ex
> +    |> Repo.get!(id)
一回しかパイプしない場合は普通に書いて下さい
```suggestion
    Repo.get!(Favorite, id)
```

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project_web/api/post_api_controller.ex
> +    with {:ok, %Post{} = post} <- Twitter.create_post(changeset, post_params) do
with 🙅

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project_web/api/post_api_controller.ex
> +    with {:ok, %Post{}} <- Twitter.update_post(post, post_params) do
with 🚫

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project_web/api/post_api_controller.ex
> +    with {:ok, %Post{}} <- Twitter.delete_post(post) do
with 🚫

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project_web/api/user_api_controller.ex
> +    with {:ok, %User{}} <- Accounts.update_user(user, user_params) do
with 🚫

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project_web/api/user_api_controller.ex
> +    with {:ok, %User{}} <- Accounts.delete_user(user) do
with 🚫

2021-04-20 05:43 UTC, MasashiYokota commented on src/lib/project_web/controllers/favorite_controller.ex
> +    with {:ok, %Favorite{}} <- Twitter.delete_favorite(post) do
with 🚫

2021-04-24 03:58 UTC, MasashiYokota requested changes
コメントしました

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/PostEdit.vue
> +        const response = await axios.put("/api/posts/" + id, {
`/api/posts/${id}`
テンプレートリテラルを使いましょう！

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/PostIndex.vue
> +            <a v-bind:href="'/posts/' + post.id + '/edit'">Edit</a>
ここもテンプレートリテラル使って下さい！

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/PostIndex.vue
> +    onMounted(getFavorites);
何回もonMountedを呼ぶんじゃなくて、一回にまとめて下さい。

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/PostShow.vue
> +    onMounted(getPost);
getPost作る必要ないのでは？

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/UserEdit.vue
> +    onMounted(getUser);
ここもgetUser吐き出す必要ないのでは？

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/UserIndex.vue
> +    onMounted(getUsers);
ここも。

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/UserShow.vue
> +    onMounted(getUser);
ここも

2021-04-24 03:58 UTC, MasashiYokota commented on src/assets/js/vue/UserShow.vue
> +    onMounted(getUser);
あと、上記のパターンが頻出していて、DRYになっていないのでstoreパターンを使ってリファクタリングしてください
https://qiita.com/tmy/items/a545e44100247c364a71
https://qiita.com/resessh/items/ab09ec925ca49d02caae

2021-04-27 09:23 UTC, shunjilin reviewed
Seems mostly good! Just some advice on other patterns that may make the code a bit easier to maintain!

I only reviewed the front end (I have to run for now), but let me know if there is any other part you would like me to review and I can review tomorrow!

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/stores/posts.js
> +        get post() {
this is ok! but not very common usage,

If you need to make this readonly, you can do:
```
return {
  posts: readonly(state.posts)
}
```
https://v3.vuejs.org/api/basic-reactivity.html#readonly

Also if your state is very big and you need to dereference all of them you can do something like:
```
return {
  ...toRefs(state)
}
```
https://v3.vuejs.org/api/basic-reactivity.html#readonly

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/vue/PostEditSub.vue
> +      const postIndex = post_list.post.findIndex((data) => data.id == post_id);
prefer to use `===` instead of `==`

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/vue/PostShowSub.vue
> +    function getPost() {
maybe you can make this a computed property? so that it only gets updated when the underlying post_list is changed
https://v3.vuejs.org/api/basic-reactivity.html#readonly

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/vue/SessionNew.vue
> +      state,
Not necessary, but if it makes it easier you can do
```
...toRefs(state)
```
so that in the template you don't have to call state. ... all the time

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/vue/UserShowSub.vue
> +    function getUser() {
same here, can use a computed

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/stores/users.js
> +        get user() {
same as the above comment in stores/post.js!

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/vue/PostEditSub.vue
> +    function getPost() {
can probably make this computed so it only gets updated when the underlying data changes

2021-04-27 09:23 UTC, shunjilin commented on src/assets/js/vue/PostNew.vue
> +    const state = reactive({
see the other comment on toRef

2021-04-27 09:29 UTC, shunjilin commented
Oh and don't forget to remove all the console.logs!

2021-05-01 07:42 UTC, MasashiYokota commented on src/assets/js/stores/posts.js
> +    }
これ、API側のデリートも一緒にやった方がよいのでは？

2021-05-01 07:42 UTC, MasashiYokota commented on src/assets/js/stores/users.js
> +    }
ここも。

2021-05-01 07:46 UTC, MasashiYokota commented
フロントエンドのテスト、全部書いていないですね。
jestを使ってすべてのテストを書いて下さい。

2021-05-15 02:31 UTC, MasashiYokota requested changes
MVCの各役割がわかっていませんね。
テキストで、MVCそれぞれの役割を回答して返信して下さい。

あと、バックエンドのテストが謎に全部コメントアウトされています。修正して下さい。

2021-05-15 02:31 UTC, MasashiYokota commented on src/assets/js/vue/PostEditSub.vue
> +    });
これはindexを取ってくるよりも、実際にほしいのは`postList.posts.value[postIndex.value]`だと思うから、こいつを返してやったほうが良いのでは？

2021-05-15 02:31 UTC, MasashiYokota commented on src/assets/js/vue/PostEditSub.vue
> +    });
あと、template内で使っているわけではないので、publicにする必要はないですね。

2021-05-15 02:31 UTC, MasashiYokota commented on src/assets/js/vue/PostIndexSub.vue
> +        post.favorites.push(1);
favoritresになんで`1`を入れているんですか？もしかして、お気に入りのカウントをしている気がするんですが、普通にカウントするなら、integerにして、インクリメントさせた方が良いですね。意味のないデータ構造は使わないで下さい。

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project/twitter.ex
> +  end
これ、未対応です

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project/twitter.ex
> +    |> Repo.get!(id)
ここも未対応

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project_web/views/favorite.view.ex
> +defmodule ProjectWeb.FavoriteView do
ファイル名が変です。確認して下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project_web/views/favorite.view.ex
> +    Twitter.get_favorite!(id)
DBへのアクセスはcontrollerでやって下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project_web/views/favorite_api_view.ex
> +    Twitter.list_favorites()
DBへのアクセスはcontrollerでやって下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project_web/views/post_api_view.ex
> +    Twitter.list_posts()
DBへのアクセスはcontrollerでやって下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project_web/views/post_api_view.ex
> +    Twitter.get_post!(id)
DBへのアクセスはcontrollerでやって下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/lib/project_web/views/user_api_view.ex
> +    Project.Accounts.get_user(id)
DBへのアクセスはcontrollerでやって下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/test/project_web/controllers/post_controller_test.exs
> +    # end
全部コメント合うとしているけどテスト書いて下さい

2021-05-15 02:31 UTC, MasashiYokota commented on src/test/project_web/controllers/post_controller_test.exs
> +    # end
他も同様です

2021-05-18 03:44 UTC, MasashiYokota commented on src/assets/js/vue/PostIndexSubFavorite.vue
> +    });
propsをstateに入れてはいけません。考え直しましょう

2021-05-18 03:45 UTC, MasashiYokota commented on src/assets/js/vue/PostIndexSubFavorite.vue
> +  props: ["post", "fav"],
`fav`とか略してはいけません。あと、snake caseとcamel caseがごっちゃになっているのですべてのファイルで確認して下さい

2021-05-18 03:46 UTC, MasashiYokota commented on src/assets/js/vue/UserShowSub.vue
> +    });
やるならgetterとかのほうが良いです。
stateにするなら値が変わるようなものだけです

2021-05-18 04:27 UTC, jeanklingler reviewed
Sorry I haven't reviewed everything yet, but submitting my comments so far. Will continue reviewing.

2021-05-18 04:27 UTC, jeanklingler commented on src/test/project_web/api/post_api_controller_test.exs
> +    test "rendering favorited post", %{conn: conn, post: post} do
typo
```suggestion
    test "rendering favorite post", %{conn: conn, post: post} do
```

2021-05-18 04:27 UTC, jeanklingler commented on src/lib/project_web/views/user_api_view.ex
> +  end
I think it is more common for JSON views to explicitly pick the fields that are getting exposed rather than forwarding the plain structs, and to use `render_many` for lists.

```elixir
 %{title: page.title}
```

See https://hexdocs.pm/phoenix/views.html#rendering-json

2021-05-18 04:27 UTC, jeanklingler commented on src/lib/project_web/views/user_api_view.ex
> +  end
However, I am not sure what the expectation is because this is a learning project. @MasashiYokota WDYT?

2021-05-18 04:27 UTC, jeanklingler commented on src/lib/project_web/views/error_view.ex
> +      :not_found ->
given the error message, this name is misleading. Shouldn't we pick `:user_not_found`?

2021-05-18 04:27 UTC, jeanklingler commented on src/lib/project_web/views/api_view.ex
> +end
probably not needed in the twitter clone, this was just a test, right?

2021-05-18 04:27 UTC, jeanklingler commented on src/lib/project_web/templates/layout/app.html.eex
> +    <script src="https://unpkg.com/http-vue-loader"></script>
it is probably best to rely on a package manager (npm / yarn) to manage dependency, using a package.json and a lock file (to make sure dependencies of dependencies are on a known version). Webpack will also handle the minification etc.
Phoenix should have it setup by default.

2021-05-18 04:27 UTC, jeanklingler commented on src/lib/project_web/router.ex
> +    # plug :protect_from_forgery
[naive question] why comment this out?

2021-05-18 04:30 UTC, jeanklingler commented on src/lib/project_web/api/post_api_controller.ex
> +        get_post = Twitter.get_post!(post.id)
Since you already have `post` available, it feels un-necessary to get it once again, WDYT?

2021-05-18 04:50 UTC, jeanklingler commented on src/lib/project_web/controllers/favorite_controller.ex
> +      |> Repo.one()
The controller (and more generally the `project_web` layer) should avoid to call ecto directly but rely on contexts in the `project` layer that handle the details of interacting with the DB.
Contexts and code organization are detailed in the [context docs](https://hexdocs.pm/phoenix/contexts.html) or in the programming Phoenix book, page 45 ("Working with contexts").

2021-05-18 04:55 UTC, jeanklingler commented on src/lib/project_web/api/post_api_controller.ex
> +    end
[nit] If you only have one expected case, you can use the match operator `=` rather than `case`.
```suggestion
    {:ok, %Post{}} = Twitter.delete_post(post) 
    send_resp(conn, :no_content, "")
```
But if you really don't expect a failure in the first place, it might be better to define a `Twitter.delete_post!` function instead.

2021-05-18 04:56 UTC, jeanklingler commented on src/lib/project_web/api/post_api_controller.ex
> +    get_post = Twitter.get_post!(id)
`get_post` is a verb and would be appropriate to name a function, but feels off for an instance of `post`.
How about simply `post`?

2021-05-18 05:16 UTC, jeanklingler commented on src/assets/js/test/PostEditSub.test.js
> +});
this would be best to move this setup block into a `setup` function within the describe.
Else jest might overwrite this before the tests actually start.

2021-05-18 05:18 UTC, jeanklingler commented on src/assets/js/stores/posts.js
> +      const response = await axios.delete(`/api/posts/${id}`);
if you are not using `response`, no need to assign it?
```suggestion
      await axios.delete(`/api/posts/${id}`);
```

2021-05-18 05:19 UTC, jeanklingler commented on src/assets/js/stores/posts.js
> +      const response = await axios.delete(`/api/posts/${id}`);
your IDE or a linter should point this out, maybe you can try to add eslint? 
Might be overkill for a learning project, but on the other hand a linter is a good learning tool...
WDYT @MasashiYokota ?

2021-05-18 05:47 UTC, jeanklingler commented on src/assets/js/vue/UserShowSub.vue
> +      const userIndex = userList.users.value.findIndex(
in this case it seems you don't need the index but the value: `.find` is probably more apropriate

2021-05-18 05:48 UTC, jeanklingler commented on src/assets/js/vue/UserNew.vue
> +          console.error(error);
in the case of an unknown error, it will fail silently which will make debug much harder.
better to always log:
```suggestion
        console.error(error);
        if (error.response.data && error.response.data.errors) {
```

2021-05-18 05:50 UTC, Hayashi1729 commented on src/lib/project_web/api/post_api_controller.ex
> +        get_post = Twitter.get_post!(post.id)
`create_post` does not load associations with `favorites` and `user`. So, need to use `get_post!` to load these associations and render json.

2021-05-18 05:51 UTC, jeanklingler commented on src/assets/js/vue/UserNew.vue
> +      errors: "",
probably best to have `null` or `{}` as default here, since `errors` doesn't seem to be a string?

2021-05-18 05:55 UTC, jeanklingler commented on src/assets/js/test/PostIndexSubFavorite.test.js
> +      expect(error.response.data.errors.user_id[0]).toEqual("このツイートはすでにお気に入り登録されています。");
[suggestion] rather than asserting within the `catch` statement, you can use `expect(() => ...).toThrow(...)` which is better suited for this use case.

2021-05-18 05:56 UTC, jeanklingler commented on src/assets/js/test/PostIndexSubFavorite.test.js
> +axios.delete.mockResolvedValue({})
better to move this in a `setup` function

2021-05-18 06:02 UTC, jeanklingler commented on src/lib/project_web/api/post_api_controller.ex
> +        get_post = Twitter.get_post!(post.id)
In this case it might be best to address this issue by having `create_post` preload associations rather than making a redundant call in the controller? But it is not such a big issue.

2021-05-18 08:58 UTC, MasashiYokota commented on src/lib/project_web/views/user_api_view.ex
> +  end
It would be better to use `render_many`! Please refactor

2021-05-18 09:00 UTC, MasashiYokota commented on src/assets/js/stores/posts.js
> +      const response = await axios.delete(`/api/posts/${id}`);
ESlist config is a bit complex. So, I think you don't have to add eslint

2021-05-18 09:31 UTC, jeanklingler commented on src/assets/js/vue/PostIndexSubFavorite.vue
> +        props.favorite.push(post.id);
You should never mutate props, those are input only.
What you want to use in this case is two-way binding (v-model), i.e. emit an event to let the parent know about the new value of `favorite`, the parent reacts and updates the prop.
https://v3.vuejs.org/guide/component-custom-events.html#v-model-arguments

2021-05-18 09:56 UTC, Hayashi1729 commented on src/lib/project_web/router.ex
> +    # plug :protect_from_forgery
To prevent invalid CSRF errors when api is requested

2021-05-19 02:24 UTC, jeanklingler commented on src/lib/project_web/views/favorite_api_view.ex
> +    favorite.favorite_api
Sorry, I don't understand what is `favorite_api`?
JSON view render functions typically return a plain map such as `%{id: foo.id, name: foo.name}`. They take a struct and pick the fields that need to be exposed, and might do some conversions / extra presentation logic.

2021-05-19 02:32 UTC, jeanklingler commented on src/assets/js/vue/PostIndexSub.vue
> +    }
I think you are handling half of the state here and the other half in the store.
Ideally you should delegate the state to the store and only worry about the presentation here.
Also, it feels wrong to just modify the state in JS without calling the API first.

2021-05-25 02:27 UTC, MasashiYokota requested changes

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/app.js
> +    components: { Index, UserIndex, UserNew, UserShow, UserEdit, PostIndex, PostNew, PostShow, PostEdit, SessionNew }
ここは改行したほうが読みやすいですね

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/stores/favorites.js
> +  }
各関数の間に改行があると嬉しいです

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/stores/favorites.js
> +  async function favoriteDelete(post) {
関数名が、英語として不自然な感じがします。
動詞から始めたほうが良いかと思います。

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/stores/posts.js
> +  }
ここも関数名考え直しましょう

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/stores/users.js
> +  }
ここも関数名考え直して下さい

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/vue/FavoriteProvider.vue
> +<template>
ディレクトリ名は、`vue`ではなく、`components`とかにした方がよいです

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/vue/PostEditSub.vue
> +<template>
コンポーネント名の`PostEditSub.vue`の`Sub`ってどういう意味ですか？
不明瞭な命名は混乱を招くので、もう一度考え直してみて下さい

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/vue/PostIndexSub.vue
> +<template>
このコンポーネント名のSubも微妙ですね。Sub禁止です 🙅 
他のコンポーネントにもあったら、全部修正して下さい

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/vue/SessionNew.vue
> +<template>
ここのコンポーネント名も微妙ですね。
コンポーネント名はページの要素なので、要素っぽい名前にしないといけません。
例えば、このコンポーネントだとSessionFormとかですね。

2021-05-25 02:27 UTC, MasashiYokota commented on src/assets/js/vue/UserEdit.vue
> +</template>
よくよく考えてみると、このパターンでいくつかのコンポーネントを作っているけど
コンポーネント分ける必要ありますか？

2021-05-29 02:54 UTC, MasashiYokota requested changes
store パターンはまだわかっていない感じがするので、もう一度調べ直して下さい！

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/FavoriteProvider.vue
> +<template>
このコンポーネントって使われていますか？

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/Index.vue
> +<template>
単にindexだと何のindexかわからないので、もう少しコンポーネント名を考え直しましょう

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/PostIndexFavorite.vue
> +<template>
これは、FavoriteFormとかの方がコンポーネントとして適切だと思います

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/PostIndexFavorite.vue
> +      return props.favorite.includes(id);
`props.post.favorites`と`props.favorite`はどう違うんですか？本質的に同じだと思うんですけど。
あと、stateの初期値をpropから受け取った値にする必要はありません。そもそも、`props.post.favorites.length`を見ればstateをカウントアップ/カウントダウンする必要ないと思うんですが。

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/favoriteKey.js
> +  return favoriteList
なぜかここでAPI callしている？
なんか使い方があまりわかっていなさそうですね。。。もう一度、storeパターンを見直して下さい

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/postKey.js
> +  return postList
ここも見直して下さい

2021-05-29 02:54 UTC, MasashiYokota commented on src/assets/js/components/userKey.js
> +  return userList
ここも見直して下さい

2021-05-29 02:59 UTC, Hayashi1729 commented on src/assets/js/components/FavoriteProvider.vue
> +<template>
今は使用していません。削除し忘れていました。

2021-05-29 07:19 UTC, MasashiYokota requested changes
細かいところですがコメントしました

2021-05-29 07:19 UTC, MasashiYokota commented on src/assets/js/components/PostIndex.vue
> +    favoriteList.getFavorite();
API callして、状態更新するのはmountでやったほうが良いです。他のファイルも確認して下さい

2021-05-29 08:08 UTC, MasashiYokota approved these changes
LGTM 👍

2021-05-29 08:50 UTC, merged